name: My First Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4.2.2
            - name: Welcome message
              run: echo "My first Github Action"
            - name: List files
              run: ls
            - name: Read file
              run: cat README.md