name: Generate ASCII Artwork
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4.2.2
            - name: List Repo Files
              run: ls -ltra
            - name: Executing Shell Script
              run: ./ascii-script.sh