name: Matrix Configuration
on:
    push:
    workflow_dispatch:
jobs:
    deploy:
        strategy:
          matrix:
            os: [ubuntu-latest, ubuntu-20.04, windows-latest]
            images: [hello-world, alpine]
        runs-on: ${{matrix.os}}
        steps:
            - name: Print Docker Info
              run: docker info
            - name: Run ${{matrix.images}} on ${{matrix.os}}
              run: docker run ${{matrix.images}}