name: Exploring Variables and Secrets
on:
    push: 
jobs:
    docker:
        runs-on: ubuntu-22.04
        steps:
            - name: Docker Build
              run: echo docker build -t ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest
            - name: Docker Login
              run: echo docker login --username=${{vars.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}
            - name: Docker Publish
              run: echo docker push ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest

    deploy:
        if: github.ref_name == 'ref/heads/main'
        needs: docker
        concurrency:
          group: production-deployment
          cancel-in-progress: false
        runs-on: ubuntu-22.04
        steps:
            - name: Run Container
              timeout-minutes: 1
              run: |
                echo docker run -d -p 8080:80 ${{vars.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/${{vars.IMAGE_NAME}}:latest
                sleep 6000