name: Exploring Variables and Secrets
on: push
jobs:
    docker:
        env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: se-omar-ahmed
            IMAGE_NAME: custom-nginx
        runs-on: ubuntu-22.04
        steps:
            - name: Docker Build
              run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
            - name: Docker Login
              env:
                DOCKER_PASSWORD: s3cUrePaSsw0rd
              run: echo docker login --username=${{env.DOCKER_USERNAME}} --password=${{env.DOCKER_PASSWORD}}
            - name: Docker Publish
              run: echo docker push ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest

    deploy:
        env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: se-omar-ahmed
            IMAGE_NAME: custom-nginx
        runs-on: ubuntu-22.04
        needs: docker
        steps:
            - name: Run Container
              run: echo docker run -d -p 8080:80 ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest